Lambda-School-Labs/labs-team-home

backend/graphql/resolvers/Message.js, backend/graphql/resolvers/Tag.js, backend/graphql/resolvers/User.js, backend/graphql/resolvers/index.js, backend/graphql/schema/Tag.js, backend/graphql/schema/Team.js, backend/graphql/schema/User.js, backend/graphql/schema/index.js, backend/models/User.js, backend/package.json, backend/yarn.lock
Co-authored-by: David Pok <david.pok@gmail.com>
Co-authored-by: zacharyarney <zachary.arney@gmail.com>
=> Add User resolver, update tag resolvers and update schemas for mutations

backend/config/index.js, backend/index.js
Co-authored-by: David Pok <david.pok@gmail.com>
Co-authored-by: zacharyarney <zachary.arney@gmail.com>
Description
Add config directory in order to increase readability and maintainability.
Type of change
Checklist:
=> Add config directory

backend/README.md, backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/Tag.js, backend/graphql/resolvers/Team.js, backend/graphql/resolvers/User.js, backend/graphql/resolvers/index.js, backend/graphql/schema/Message.js, backend/graphql/schema/MsgComment.js, backend/graphql/schema/Team.js, backend/graphql/schema/User.js, backend/models/Message.js, backend/models/MsgComment.js
Co-authored-by: David Pok <david.pok@gmail.com>
Co-authored-by: zacharyarney <zachary.arney@gmail.com>
Finish resolvers and have prototype built out for API.
Testing in the GraphQL playground that comes with Apollo.
- [] I have added tests that prove my fix is effective or that my feature works
=> Add Team, Message, and MsgComment resolvers & Backend documentation

frontend/README.md
I've included setup instructions for the frontend.
Added instructions
=> FrontEnd Readme

backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/Tag.js, backend/graphql/resolvers/Team.js, backend/graphql/schema/Message.js, backend/graphql/schema/MsgComment.js, backend/graphql/schema/Team.js
Added mongoose populate() method to resolvers to behave more in a more compatible way with GraphQL
read more here: https://mongoosejs.com/docs/populate.html
Apollo GraphQL playground.
=> Added mongoose populate() method to GraphQL resolvers

backend/README.md, backend/config/index.js, backend/graphql/resolvers/Tag.js, backend/graphql/resolvers/Team.js
Makes back end README.md more descriptive. It now has instructions on how to set up a MongoDB server to run the app. A visual representation of the folder/file structure has also been added, with comments on everything's purpose. 
The Team resolver has also been slightly changed in order to make its return values consistent with all the others.
The README changes have been read over for spelling/punctuation. Team resolver changes tested in GraphQL playground.
- [] My code has been reviewed by at least one peer
=> Back end cleanup

frontend/README.md
Updated frontend readme to include yarn install
=> Update frontend readme

ios/TeamHome/TeamHome/Models/Mock json/TeamExample.json
Update json for mock json file
Used json validator online to check json.
=> Update other json file.

ios/TeamHome/TeamHome/Models/Mock json/TagExample.json
Updating another json file.
Used online json validator.
=> Updating another json file.

backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/Tag.js, backend/graphql/resolvers/Team.js
MongoDB was returning an error when adding items because of the populate() method.
Tested with GraphQL
- [] I have added tests that prove my fix is effective or that my feature works
=> Fixes mongodb bug

backend/config/index.js, backend/package.json, backend/yarn.lock, frontend/src/App.css
Set up auth0 to check for valid JWT on requests.
Tested with Apollo GraphQL playground.
=> Setup auth0 on backend

backend/README.md
Just an update to the backend readme file that adds info on Auth0, Sendgrid and Twilio as well as some formatting.
=> Updates backend readme with info on using Auth0, Sendgrid Twilio locally

frontend/src/App.js
Unbreaks dev by uncommenting import of LandingView in App.js
=> uncomments landingview import in App.js

.prettierignore, frontend/src/MessageBoard/components/AddMessage.js, frontend/src/MessageBoard/components/MessageBoard.js
When adding a new message an alert now pops up and the page refreshes and shows the new message
Tested with localhost
=> Show new messages

backend/config/index.js, backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/Tag.js, backend/graphql/resolvers/Team.js, backend/graphql/resolvers/User.js, backend/graphql/schema/Message.js, backend/graphql/schema/MsgComment.js, backend/graphql/schema/Tag.js, backend/graphql/schema/Team.js, backend/graphql/schema/User.js, backend/package.json, backend/yarn.lock
- Resolver deletion behavior has been updated so that when a team is deleted, so are all of its messages and comments. When a user is deleted, so are all of their messages and comments. When a message is deleted, so are are of its comments, etc.
- A user's information is now automatically retrieved from auth0 when they first sign up. First Names Last Names, and Avatars will no longer be stored as null,
- All previous resolvers that took a user ID as an input don't do it any longer as it is now retrieved automatically through the context from the JWT https://www.apollographql.com/docs/apollo-server/essentials/data.html#context
- When a comment is added to a message, all subscribed users will now receive an email notification (text message isn't implemented since it doesn't work with a …
=> Update resolvers [to be merged with #92 and #93]

frontend/src/MessageBoard/components/MessageBoard.js
Added sorting based on updatedAt timestamp
Tested locally
=> Sorting MessageBoard.js

frontend/src/MessageBoard/components/MessageBoard.js
Added sorting based on updatedAt timestamp
Tested locally
=> Sort MessageBoard.js

backend/graphql/resolvers/Team.js
Fixes bugs with the findTeam and inviteUser resolvers that were causing them to be broken.
Apollo playground.
=> Fix bugs with team resolvers

backend/graphql/resolvers/Team.js, backend/stripe/routes/index.js, backend/stripe/routes/payment.js, frontend/src/SettingsView/BillingView/BillingView.js
Setup for graphql/stripe integration on the backend
tested on localhost
=> Features backend graphql/stripe

backend/graphql/resolvers/Team.js, backend/graphql/schema/Team.js, frontend/src/SettingsView/BillingView/BillingView.js
Adds frontend connection for graphql to stripe
tested in localhost and graphiQL client thing
Co-authored-by: koennecker <koenneckerb@gmail.com>
=> features frontend graphql stripe

frontend/src/SettingsView/BillingView/BillingView.js, frontend/src/SettingsView/components/forms/FormInput.js, frontend/src/SettingsView/components/tabs/SingleTab.js
removed some unnecessary code and made a few notes 
tested in localhost
=> Features settings/housekeeping

backend/config/index.js, backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/Team.js, backend/graphql/resolvers/User.js, backend/graphql/schema/Message.js, backend/graphql/schema/MsgComment.js, backend/graphql/schema/Team.js, backend/graphql/schema/User.js, backend/index.js, backend/models/Message.js, backend/models/MsgComment.js, backend/models/User.js
- Removes automatic user creation, which will now be handled client-side. Previously, a GET request made to the auth0 API was causing user sign ups on iOS to break. The firstName, lastName, and email property of the User model has again been made required by the MongoDB model and non-nullable in the GraphQL schema.
- Updates message model to only have one tag instead of multiple tags. Comments now have a property for images.
- Adds mutations for liking/unliking comments, subscribing/unsubscribing to posts, leaving teams, and kicking users. These actions were previously possible with other mutations, but required complex client-side logic that would be better handled by the backend.
Tested with the GraphQL playground.
=> [to be merged with #138] Update DB models and mutations

backend/config/index.js, backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/Team.js, backend/graphql/resolvers/User.js, backend/graphql/schema/Message.js, backend/graphql/schema/MsgComment.js, backend/graphql/schema/Team.js, backend/graphql/schema/User.js, backend/index.js, backend/models/Message.js, backend/models/MsgComment.js, backend/models/User.js, frontend/src/MessageBoard/components/Message.js, frontend/src/MessageBoard/components/MessageDetail.js, frontend/src/SettingsView/containers/SettingsView.js, frontend/src/constants/fragments.js, frontend/src/constants/mutations.js, frontend/src/constants/queries.js, frontend/src/utils/PrivateRoute.js, frontend/src/utils/PublicRoute.js
Corresponding compatibility changes for #137 
- Fixes bug with subscriptions that was causing them to break
- Redirects new users to the settings page on login to set their first name, last name and email address.
- Changes queries and mutations where applicable to be in line with the schema/model updates on the backend.
Tested with the GraphQL playground.
=> Update DB models and mutations - corresponding front end changes

frontend/src/index.css
Included montserrat in index css file
=> Included montserrat in index css file

backend/config/index.js
Mongoose no longer uses useFindAndModify
Tested locally
=> Fix mongoose deprecation

frontend/src/SettingsView/components/forms/FormButton.js, frontend/src/SettingsView/containers/SettingsView.js
The form was not submitting due to a malformed button element
React dev environment.
=> Fix settings page bug

backend/config/apollo-server.js, backend/config/express-middleware.js, backend/config/index.js, backend/config/mongo.js, backend/graphql/schema/index.js
Now there are new files in the config directory, 'express-middleware', 'apollo-server', and 'mongo' that each export a function that initialize their respective parts of the server.
Tested with node server.
=> Modularize backend config

backend/README.md
Updated to include Stripe and Auth0 keys
I wrote instructions while doing it myself
=> Update README.md - backend

frontend/README.md
Adds security notes about some possible vulnerabilities in FilePond's type validation to the Front End README
=> Adds security notes about FilePond type validation to front end README

frontend/src/MessageBoard/components/AddMessage.js, frontend/src/MessageBoard/components/MessageBoard.js
Adds Material UI styles to the Add Message form.
React dev environment.
=> Style add message form

frontend/package.json, frontend/src/MessageBoard/components/AddMessage.js, frontend/src/MessageBoard/components/Invites.js, frontend/src/MessageBoard/components/MessageDetail.js, frontend/src/MessageBoard/components/UserList.js, frontend/src/MessageBoard/components/mutations/comments.js, frontend/src/constants/fragments.js, frontend/yarn.lock
- Makes the Message Detail and User List responsive. They have been refactored to use the Material UI Dialog component and I have removed Reach Dialog as a dependency.
- Updates the responsive styles for the Add Message and Invite modals to be less squished on smaller screens
- Refactor the mutations on MessageDetail to be less verbose
React dev environment.
=> Modal Responsive Styles

backend/graphql/resolvers/Message.js
The resolver code used the old name "tags" instead of "tag" and was causing an error.
Node server.
=> Fix tags populating bug

frontend/src/MessageBoard/components/AddMessage.js, frontend/src/MessageBoard/components/MessageBoard.js, frontend/src/MessageBoard/components/mutations/messages.js, frontend/src/constants/fragments.js, frontend/src/constants/queries.js
Implements adding tags to messages.
React dev environment.
=> Add Tags to Messages

frontend/src/DashboardView/components/TeamList/TeamList.js
Changed TeamList.js to a state component to handle input via state.
Tested locally
=> Fix add team bug

backend/graphql/resolvers/Team.js
- inviteUser resolver now throws an error for non-premium teams if they try to add a user when the team is at the free limit of 5
Local node server.
=> Add Paywall to Backend

frontend/.gitignore, frontend/src/SettingsView/BillingView/BillingTeamCard.js, frontend/src/SettingsView/BillingView/BillingView.js, frontend/src/SettingsView/styles/container.styles.js
Adds basic styling to the team cards in the billing view. User feedback is proving difficult. Styled-components isn't passing props through. Must be some sort of structural problem I'm missing.
Manually locally
=> Billing page styling (no user feedback yet)

frontend/src/MessageBoard/components/ActivityTimeline.js, frontend/src/MessageBoard/components/GeneralActivity.js, frontend/src/MessageBoard/components/Message.js, frontend/src/MessageBoard/components/MessageBoard.js, frontend/src/MessageBoard/containers/MessageBoardContainer.js
Fixed sorting on message board and activity timeline
=> Fixed sorting on message board and activity timeline

frontend/src/DashboardView/components/TeamList/TeamList.js, frontend/src/DashboardView/components/TeamList/TeamList.styles.js
=> Style tweaks

frontend/src/SettingsView/BillingView/BillingView.js, frontend/src/SettingsView/styles/container.styles.js
Styling fixes for the billing page
Manually locally
=> Billing page styling

frontend/src/SettingsView/containers/SettingsView.js
Fixes bug that caused the app to crash for new users.
Locally
=> Fix new user bug

frontend/src/Nav/styles/index.js
Removed transparency from navbar.  Added global button styles to mobile dropdown buttons.
=> Removed transparecny of navbar.  Added styles to mobile buttons

frontend/src/MessageBoard/containers/MessageBoardContainer.js
Added comments to the code base for clarity
DOCUMENTATION ONLY
- [x ] Complete, tested, ready to review and merge
=> Added comments to MessageBoardContainer

ios/README.md
=> Update README.md for iOS

.gitattributes
adds auto-resolving file for *.pbxproj file types
=> adds auto-resolving file for *.pbxproj file types

backend/config/apollo-server.js, frontend/src/Auth/Auth.js
=> this is a frivolous update, sorry. just testing if this works.

frontend/package.json, frontend/src/MessageBoard/components/MessageBoard.js, frontend/src/index.js
=> fixed a few pointer bugs. was pointing to the wrong backend

backend/config/apollo-server.js, backend/graphql/resolvers/User.js, backend/models/User.js
comented out auth for user and commmented out sub in user resolver
=> commenting out code

backend/config/apollo-server.js
typo on context in the apollo-server.js
=> fixed context typo

backend/config/apollo-server.js, backend/graphql/resolvers/User.js
=> fixing typos

backend/config/apollo-server.js, backend/graphql/resolvers/User.js
uncommenting authentication to test fixes applied to backend deployment
=> uncommenting authentication

backend/config/apollo-server.js
small change to auth0 url ending for /api/v2
=> small addition to url for auth0

frontend/README.md
Various typos and corrections to invalid data.
=> Update frontend readme for clarity

frontend/src/DashboardView/components/TeamList/TeamCard/TeamCard.js, frontend/src/DashboardView/components/TeamList/TeamCard/index.js, frontend/src/DashboardView/components/TeamList/TeamList.js, frontend/src/DashboardView/components/TeamList/index.js
Added comments to all components in frontend/DashboardView
=> Frontend Documentation --- DashboardView/Components

frontend/src/DashboardView/components/TeamList/TeamCard/TeamCard.js, frontend/src/DashboardView/components/TeamList/TeamCard/index.js, frontend/src/DashboardView/components/TeamList/TeamList.js, frontend/src/DashboardView/components/TeamList/index.js, frontend/src/LandingView/components/LandingLogoBanner.js, frontend/src/LandingView/containers/LandingView.js
Added more comments related to the landing page.
=> Landing View comments

backend/README.md
trivial: updated the Readme.md
=> Update Backend readme

backend/config/apollo-server.js, frontend/src/Auth/Auth.js
This is a working local deployment of a local development version, with Auth0 working and login working.
=> Working local development version

frontend/src/Nav/NavResp.js
=> uncommented handlelogin function in navresp.js

backend/config/apollo-server.js, frontend/src/MessageBoard/containers/MessageBoardContainer.js, frontend/src/Nav/Nav.js, frontend/src/Nav/NavResp.js, frontend/src/Nav/components/LandingButton.js, frontend/src/Nav/styles/index.js
I fixed the console warning about not nesting a button in a button. 
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] Complete, tested, ready to review and merge
=> Document framework

frontend/src/MessageBoard/components/ActivityTimeline.js, frontend/src/MessageBoard/components/UserList.js, frontend/src/MessageBoard/containers/MessageBoardContainer.js
Fix warning where variable is defined but not used
=> Fix warning where variable is defined but not used

backend/config/apollo-server.js, backend/graphql/resolvers/Document.js, backend/graphql/resolvers/Folder.js, backend/graphql/resolvers/index.js, backend/graphql/schema/Document.js, backend/graphql/schema/Folder.js, backend/graphql/schema/index.js, backend/models/Document.js, backend/models/Folder.js
Built the Folder model/schema/resolver
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
- [x ] Complete, but not tested (may need new tests)
=> Folder model schema resolver

backend/config/express-middleware.js, backend/graphql/schema/Document.js
Previous cors fix did not solve the issue, and might have messed up the currentuser query. Reverting.
=> unfortunately, the cors fix was not a fix. reverting.

backend/config/apollo-server.js, backend/graphql/schema/Document.js
Another try to see what is afflicting netlify.
=> retrying commit message - commenting out variables 

frontend/src/Content/ContentContainer.js, frontend/src/Content/MessageBoard/MessageBoard.js, frontend/src/Content/components/TeamInfo.js
Created a new component, TeamInfo, and moved all the team info from MessageBoard.js to it.  
=> Add new component TeamInfo, refactored out of MessageBoard

backend/graphql/resolvers/Document.js, backend/graphql/resolvers/Folder.js, backend/graphql/schema/Document.js
=> tweaks to folders resolver

backend/config/apollo-server.js, backend/graphql/resolvers/Document.js, backend/graphql/resolvers/Folder.js, backend/graphql/schema/Document.js
Fixed merge issue and added new functionality to Document.js.
=> Backend kai

frontend/src/Content/ContentContainer.js, frontend/src/Content/DocumentsTab/DocsButtonMenu.js, frontend/src/Content/DocumentsTab/Folders.js, frontend/src/Content/DocumentsTab/TabContainer.js
Since our Documents functionality will have a lot of things added to it, everything has been moved into its own respective components to keep the amount of lines in each file to a minimum. At least for now.
=> Organizational Changes for Documents Tab-related items

backend/config/apollo-server.js, backend/graphql/resolvers/Document.js, frontend/src/LandingView/containers/LandingView.js, frontend/src/index.js
Fixed env error in index.js frontend. auth0 should send a user back to the db now.
=> fixed env issue. auth should be okay.

frontend/src/Content/ContentContainer.js, frontend/src/Content/MessageBoard/MessageBoard.js, frontend/src/Content/MessageBoard/MessageDetail.js
Refactored MessageDetails to make it more clear.
=> Refactor MessageDetails for clarity

frontend/src/Content/DocumentsTab/Documents.js, frontend/src/Content/DocumentsTab/Folders.js, frontend/src/Content/DocumentsTab/TabContainer.js, frontend/src/constants/fragments.js, frontend/src/constants/queries.js
Documents now show up underneath folders inside of the Documents Tab.
=> Adds ability to see Documents in Documents Tab

frontend/src/Content/DocumentsTab/AddFolder.js, frontend/src/Content/DocumentsTab/DocsButtonMenu.js, frontend/src/Content/DocumentsTab/Folders.js, frontend/src/Content/DocumentsTab/TabContainer.js, frontend/src/Content/MessageBoard/AddMessage.js, frontend/src/Content/MessageBoard/MessageDetail.js
Added the GUI components for adding a folder. 
*There may be merge conflicts with this merge* 
Please carefully review!
=> First working GUI version of adding a new folder

backend/graphql/resolvers/DocComment.js, backend/graphql/resolvers/Folder.js, backend/graphql/schema/DocComment.js, backend/graphql/schema/Document.js, backend/graphql/schema/Folder.js, backend/models/Document.js, backend/models/Folder.js
built out DocComment model/schema/resolver
=> Doc comment model schema resolver

frontend/src/SettingsView/containers/SettingsView.js, frontend/src/SettingsView/styles/container.styles.js
The inputs of SettingsView are now neater than ever before
=> Adjusted styles of SettingsView

backend/graphql/resolvers/Document.js, frontend/src/Content/DocumentsTab/DnD/DnDTest/index.js, frontend/src/Content/DocumentsTab/DnD/Draggable/index.js, frontend/src/Content/DocumentsTab/DnD/Droppable/index.js, frontend/src/Content/DocumentsTab/Documents.js, frontend/src/Content/DocumentsTab/Folders.js
initial implementation for DnD; currently able to drag documents into folders and from folder to folder and back out the folder.
it is not persistent at this time
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
=> initial implementation of React DnD

backend/graphql/resolvers/Document.js, frontend/src/App.js, frontend/src/Content/DocumentsTab/AddDocument.js, frontend/src/Content/DocumentsTab/DocsButtonMenu.js, frontend/src/Content/DocumentsTab/FolderDetails.js, frontend/src/Content/DocumentsTab/Folders.js, frontend/src/Content/mutations/documents.js, frontend/src/Content/mutations/folders.js, frontend/src/constants/mutations.js
=> Add document add GUI

frontend/README.md, frontend/src/Content/ActivityTimeline/Activity.js
Improve the readme for the front end deployment
=> Activetly timeline and readme updates

frontend/src/DashboardView/components/TeamList/TeamList.js, frontend/src/DashboardView/components/TeamList/TeamList.styles.js
The input section where you can add a Team now adds a team upon pressing the enter key.
=> Changes to Team Input

backend/graphql/resolvers/Document.js, backend/graphql/schema/Document.js, frontend/src/Content/DocumentsTab/DocumentDetails.js, frontend/src/Content/DocumentsTab/Documents.js, frontend/src/Content/DocumentsTab/Folders.js, frontend/src/Content/DocumentsTab/TabContainer.js, frontend/src/Content/mutations/documents.js, frontend/src/constants/mutations.js
Adds the initial document modal.
=> Add an intitial documents modal

backend/graphql/schema/Document.js, frontend/src/Content/DocumentsTab/DocumentDetails.js, frontend/src/Content/MessageBoard/MessageDetail.js, frontend/src/Content/mutations/doccomments.js, frontend/src/Content/mutations/documents.js, frontend/src/Content/mutations/messages.js, frontend/src/constants/fragments.js, frontend/src/constants/mutations.js, frontend/src/constants/queries.js
Add fully functional (but silly poorly styled) document modal.
=> Add DocComments and Document modal

frontend/src/Content/DocumentsTab/DocumentDetails.js, frontend/src/Content/DocumentsTab/FolderDetails.js, frontend/src/Content/mutations/folders.js, frontend/src/constants/mutations.js, frontend/src/constants/queries.js
Add folder modal, poorly styled
=> Added folder modal

backend/graphql/resolvers/Document.js, frontend/src/Content/DocumentsTab/DnD/Droppable/index.js, frontend/src/Content/DocumentsTab/Documents.js, frontend/src/Content/DocumentsTab/Folders.js, frontend/src/constants/fragments.js
might have finally got the persistence and changes of doc from folder to folder and back out again working; thanks to Kai, Bondor and Eileen
made changes to the addDocument resolver to fix another issue that was happening
various other small tweaks
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
- [x ] Complete, but not tested (may need new tests)
=> New dnd attempt

frontend/src/Content/ActivityTimeline/Activity.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/constants/fragments.js
Activity Timeline now displays all activities including documents, document comments and folders.
=> Updates Activity Timeline (revised)

frontend/src/Content/DocumentsTab/Documents.js, frontend/src/Content/DocumentsTab/Folders.js
Adds the ability to sort folders and documents by newest or oldest.
=> Document/ Folder sort added

frontend/src/Content/DocumentsTab/DocsButtonMenu.js
=> Fix add button toggling

backend/graphql/resolvers/Document.js, backend/graphql/schema/Document.js, backend/models/Document.js
Adds the ability to add a tag by including it in the Documents schema, model, and resolver in the backend.
=> Adds Tags to documents schema/models/resolvers

backend/graphql/resolvers/Document.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/Content/DocumentsTab/Documents.js, frontend/src/Content/DocumentsTab/FolderDetails.js, frontend/src/Content/mutations/folders.js
Add ability to delete folder and set documents folder to null
Other refactoring
=> Add ability to delete folder and set documents folder to null

frontend/src/Content/DocumentsTab/DocumentDetails.js, frontend/src/Content/DocumentsTab/Documents.js, frontend/src/constants/fragments.js, frontend/src/constants/mutations.js
This adds functional subscriptions to documents
=> Add subscriptions

frontend/src/Content/ActivityTimeline/Activity.js, frontend/src/Content/DocumentsTab/DocumentDetails.js, frontend/src/Content/DocumentsTab/FolderDetails.js, frontend/src/Content/MessageBoard/MessageDetail.js, frontend/src/DashboardView/components/TeamList/TeamList.styles.js
All new features are now a little more responsive.
=> added changes to styling for easier mobile use

backend/graphql/resolvers/DocComment.js, backend/models/Team.js, frontend/src/Content/DocumentsTab/DocumentDetails.js
Removed comments from Team.js in backend
=> Removed some commented out code that is not necessary for reference anymore.

frontend/src/Content/ActivityTimeline/Activity.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js
Activity Timeline now displays comments again.
=> Fixes to Activity Timeline

backend/graphql/resolvers/Team.js, frontend/src/Content/ActivityTimeline/Activity.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/Content/DocumentsTab/DocumentDetails.js, frontend/src/Content/DocumentsTab/FolderDetails.js, frontend/src/Content/DocumentsTab/Folders.js
Fix a bunch of console warnings
=> Warning fixes

backend/graphql/resolvers/Folder.js
Commented out a line code code with folders.
=> commented out a line of code made redundant.

backend/graphql/resolvers/Event.js, backend/graphql/resolvers/Folder.js, backend/graphql/schema/Event.js, backend/graphql/schema/index.js, backend/models/Event.js, frontend/src/Content/ActivityTimeline/README.md
Add Events resolvers, model, and schema for Activity Timeline refactor
=> Add Events resolvers, model, and schema

frontend/package.json, frontend/src/Content/DocumentsTab/Documents/DocumentDetails.js, frontend/yarn.lock
The documents modal now has styling that focuses more on the document.
Also adds `styled-icons` dependency for more icon shenanigans.
=> Changes to Documents Modal

frontend/src/Content/DocumentsTab/Doc.js, frontend/src/Content/DocumentsTab/Documents/DocumentContainer.js, frontend/src/Content/DocumentsTab/Folders/Folder.js, frontend/src/Content/DocumentsTab/Folders/FolderDetails.js, frontend/src/Content/mutations/documents.js
Resolved errors for Drag and Drop; implemented refetchQueries to rerender components. It looks laggy as it takes a sec for component to update with newest data.
Documents should update to reflect where they have been dragged to.
Place a document was dragged from updates to not show the removed document any longer.
=> Latest react dnd

frontend/package.json, frontend/src/App.js, frontend/src/Content/DocumentsTab/Folders/Folder.js, frontend/yarn.lock
=> testing touch support

frontend/src/Content/MessageBoard/Message.js, frontend/src/Content/MessageBoard/MessageBoard.js, frontend/src/Content/MessageBoard/MessageDetail.js, frontend/src/Content/TeamOptions/TeamDetails.js, frontend/src/GlobalStyles.js
- The gradient that haunts me has been removed. Long live the purple.
- Changes the size of fonts for Titles, Comments, and Tags
- Location of Tags and Comments have been switched
- No longer shows a preview of the Message's content
- Sort form has been moved to the right, similar to the sort forms in the Documents Tab
- Modal has been styled to look more like the Document Details modal
- Team Name now has a bigger font
- Button Options for Users in a team are now slightly more centered
=> More Modal Style Changes

backend/graphql/resolvers/Document.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/Content/DocumentsTab/Documents/AddDocument.js, frontend/src/Content/DocumentsTab/Documents/DocumentContainer.js, frontend/src/Content/DocumentsTab/Documents/DocumentDetails.js
This fixes the add document modal. 
Heck yeah.
=> Fix add document

backend/graphql/resolvers/DocComment.js, backend/graphql/resolvers/Document.js, backend/graphql/resolvers/Event.js, backend/graphql/resolvers/Folder.js, backend/graphql/resolvers/Message.js, backend/graphql/resolvers/MsgComment.js, backend/graphql/resolvers/ResolverHelpers.js, backend/graphql/resolvers/Team.js, backend/graphql/resolvers/index.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/Content/TeamOptions/TeamDetails.js, frontend/src/DashboardView/components/TeamList/TeamList.js
This adds a bunch of code that was removed. 
PLEASE PLEASE PLEASE FULLY REVIEW!!
=> Re-implement a bunch of things

frontend/src/Content/DocumentsTab/Doc.js, frontend/src/Content/DocumentsTab/Documents/DocumentCommentDetails.js, frontend/src/Content/DocumentsTab/Documents/DocumentContainer.js, frontend/src/Content/DocumentsTab/Documents/DocumentDetails.js, frontend/src/Content/DocumentsTab/Folders/AddFolder.js, frontend/src/Content/DocumentsTab/Folders/Folder.js, frontend/src/Content/DocumentsTab/Folders/FolderDetails.js
Mutation Refactors
-Doc.js
-DocumentContainer.js
-Folder.js
-FolderDetails.js
-DocumentCommentDetails.js
- centered documentDetails dropdown
=> Refactoring

frontend/src/Content/ActivityTimeline/ActivityModal.js, frontend/src/Content/DocumentsTab/Documents/DocumentDetails.js, frontend/src/Content/MessageBoard/MessageDetail.js
=> Add presentable activity modal

backend/graphql/resolvers/Event.js
Changed event.js so that addEvent returns something instead of null.
=> adding last changes for event.js so that addEvent returns something instead of null

README.md, frontend/FRONTEND_BUG_REPORT.md, frontend/package.json, frontend/src/App.js, frontend/src/Content/DocumentsTab/Documents/DocumentCommentDetails.js, frontend/src/Content/DocumentsTab/Documents/DocumentDetails.js, frontend/src/Content/MessageBoard/MessageDetail.js, frontend/yarn.lock
worked on various bugs; check out the commit messages for a bit more clarification
=> Nedim refactors

backend/README.md, backend/__tests__/mock.js
this is a test pull request for my new branch, kais-frontend. it changes the readme to reflect the beginning of the backend tests (currently halted for lack of progress), and adds a dummy test inside a new folder called "__tests__""
=> added a mock resolver test in the backend

frontend/src/Content/ActivityTimeline/ActivityModal.js, frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/Content/DocumentsTab/Documents/AddDocument.js, frontend/src/Content/MessageBoard/AddMessage.js, frontend/src/Content/TeamOptions/TeamDetails.js, frontend/src/DashboardView/components/TeamList/TeamCard/TeamCard.styles.js, frontend/src/constants/queries.js
Add style to team list
Bug fix
=> Add style to team list, fix bug when adding a tag to a message or doc

frontend/src/Auth/Auth.js, frontend/src/Content/ActivityTimeline/Activity.js, frontend/src/Content/ActivityTimeline/ActivityCartoon.js, frontend/src/Content/DocumentsTab/Documents/DocumentDetails.js, frontend/src/Content/DocumentsTab/Folders/FolderDetails.js, frontend/src/Content/MessageBoard/MessageDetail.js, frontend/src/Content/TeamOptions/TeamDetails.js, frontend/src/LandingView/components/BottomContent.js, frontend/src/LandingView/components/Pricing.js, frontend/src/LandingView/components/footer.js, frontend/src/LandingView/styles/BottomStyled.js, frontend/src/LandingView/styles/LogoBannerStyled.js, frontend/src/Nav/Nav.js, frontend/src/Nav/NavResp.js
- Activities are now a little wider
- Icons have been moved into a separate container div
- Icons have now been centered in relation to the Activity Card
- Fixes the bug where the sweet scrollbar no longer appeared due to the addition of logic for full screen modals
- Adds a lot more content to the landing page
- Adds a placeholder for iOS video content
- Styling has been changed so that it is more consistent with the rest of the site
- Footer content has been replaced with more relevant content
- Adds Styling for all new content in the Landing Page
- Removes `mediaQueryFor` import so that the terminal will no longer warn about that
- Replaces the old Sveza logo text with the new Arq logo text
=> The Big Landing Page Update [feat. Kai]

frontend/src/Content/ActivityTimeline/ActivityTimeline.js, frontend/src/Content/DocumentsTab/Folders/FolderDetails.js
- added icons to document title inside folder details view
- commented out ability to sort "Team" in the activity timeline
=> Tweaks more

frontend/src/LandingView/components/BottomContent.js
=> Remove sveza

frontend/src/LandingView/components/BottomContent.js, frontend/src/LandingView/styles/BottomStyled.js
Added back some text for benefits card, added back some removed margin space on bottom of landing pane, and a few other tweaks. still working to fix responsiveness, but most of the fires are out now.
=> Kais frontend- Small fixes and added back mistakenly removed content

frontend/src/LandingView/components/BottomContent.js, frontend/src/LandingView/components/footer.js, frontend/src/LandingView/styles/BottomStyled.js, frontend/src/index.css
Huge list of changes, too much to mention here. Changed background color to a shade lighter, made multiple media queries and changed text card heights, all kinds of stuff. check it out.
=> thanks to eileen, managed to get the landing somewhat responsive
